services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  igloo:
    build:
      context: .
      dockerfile: Dockerfile
    image: igloo:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      IGLOO_POSTGRES_URI: postgres://postgres:postgres@postgres:5432/mydb
      IGLOO_PARQUET_PATH: /app/dummy_iceberg_cdc/
      IGLOO_CDC_PATH: /app/dummy_iceberg_cdc

volumes:
  pgdata:
